### ISSUE TITLE
Current highlighted matches flicker when moving to the next/prev match

### ISSUE THREAD

**Issue by mroavi** [pgdouyon/vim-evanesco#19] opened 2021-08-04 19:18 UTC
I'm running Neovim 0.5. The flickering is subtle but nevertheless, a little annoying. Is there a way to fix it? Thanks for the plugin by the way. It improves vim's/neovim's defaults greatly!

**Comment by pgdouyon** [comment] 2021-08-04 21:39
I'm unable to reproduce any flickering using Neovim 0.5 on macOS using iTerm2. What OS and terminal emulator are you using and can you include a gif or screencast of the behavior you're seeing?

**Comment by mroavi** [comment] 2021-08-04 21:52
I'm using Neovim 0.5 on Manjaro and Alacritty as terminal. Here is a video:

https://user-images.githubusercontent.com/19517248/128265613-4b74a3fd-ec00-46dd-8281-e25b70430501.mp4

It's subtle. I guess is dependent on the number of matches present in the file (there are more `use` words below in that file that are not being displayed, 51 in total)

EDIT: I tested the flickering with 1000 `use` words to the file, but the flickering did not get worse.

**Comment by pgdouyon** [comment] 2021-08-04 22:08
That's strange, GitHub won't let me view or download the video for some reason.

My guess would be that the flickering happens because evanesco disables and then re-enables the `hlsearch` option when moving between matches. But since I can't reproduce the flicker I would guess it's showing up on your machine either due to your Neovim configuration or differences in how macOS+iTerm renders the TUI compared to Manjaro+Alacritty.

Can you reproduce the flicker with a minimal init.vim config that loads only evanesco and no other plugins and also doesn't change any default options or settings?

**Comment by mroavi** [comment] 2021-08-04 22:19
I tried to reproduce the flickering with this minimcal config:

```vim
" test.vim
" run with: nvim -u test.vim

set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'pgdouyon/vim-evanesco'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
```

The outcome is that I can't reproduce the flickering! This means that there is probably some kind of clashing with another plugin. I'll try to find out which one it is.

**Comment by mroavi** [comment] 2021-08-04 22:32
I still see the flickering even after disabling all my plugins and custom configuration. This makes me think that the clashing happens with something that is set by Neovim's default config (which I guess does not get executed if I start Neovim with `nvim -u test.vim`.

Really strange that you cannot watch the video. I tried opening it in Chrome in an incognito window and it worked.

**Comment by mroavi** [comment] 2021-08-04 22:46
I pinpointed the problem! The flickering occurs when I have vim options at the end of the file ensuring that folds (specified with markers) are initially closed when I open the file.

Try running evanesco with the minimal config above and with this text in the buffer. Save the buffer with a `.vim` extension first:
```vim
" lorem.vim
Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet
{{{1
Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet
}}}
-- vim:set foldenable foldmethod=marker:
```

**Comment by pgdouyon** [comment] 2021-08-05 18:57
Thank you for digging into this, I was able to reproduce the bug with the minimal config and have a change set that I think fixes the bug.

Can you try using the `flicker-bug` branch and let me know if you still see the flickering when moving between matches? You can use the modified config below to test:
```vim
" test.vim
" run with: nvim -u test.vim

set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'pgdouyon/vim-evanesco', {'branch': 'flicker-bug'}
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
```

**Comment by mroavi** [comment] 2021-08-05 19:37
Problem fixed. Thanks!!

**Comment by pgdouyon** [comment] 2021-08-05 19:40
Merged the fix into master, thanks again for helping with this bug!

**Closed as completed** 2021-08-05 19:40 UTC
